//@host = http://localhost:3000
@host = https://cryptic-bastion-36225.herokuapp.com

// Gets all todos
GET {{host}}/todos
content-type: application/json
#x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmRlNTk0OGNhMmM5NzExNzgzYzZlZjQiLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTQxMjk4NTA0fQ.rx4_8isR-akmnPDz06fBi9ExDyJ-zZvGCbnjhI_2brg
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmRlNTljN2NhMmM5NzExNzgzYzZlZjciLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTQxMjk4NjMxfQ.BALh2DHjnUhpLto_iMZMvIUhIJZ6yUzb_KzRGDoo18M


###

// Posts a single todo
POST {{host}}/todos
content-type: application/json
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmRmN2VhYjZjY2NlNDAwMTYzMTgxZjciLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTQxMzczOTcwfQ.s3zQak8TUs6hoDcxfarR37RGxF3__5B7QXyArO_oq2s

{
    "text": "Hoje estamos felises denovo"
}

###

// Get a single todo
GET {{host}}/todos/5bd77a8f4a402f119ce879df

###

// Deletes a single todo
DELETE {{host}}/todos/5bd7a1b01214e9fa7771818a

###

// Updates a single todo 5bd91253bdcb6d48cc09be9d
PATCH {{host}}/todos/5bd9a6e380da1e3b5845c424
content-type: application/json

{
    "completed": true
}