//@host = http://localhost:3000
@host = https://cryptic-bastion-36225.herokuapp.com

// Gets all todos
GET {{host}}/todos
content-type: application/json
#x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmRlNTk0OGNhMmM5NzExNzgzYzZlZjQiLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTQxMjk4NTA0fQ.rx4_8isR-akmnPDz06fBi9ExDyJ-zZvGCbnjhI_2brg
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmRmODY2MTVhNzgxMTAwMTY5ZTY2NWYiLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTQxMzc1NTkxfQ.E1yU4fBxX9NmCsAcZBx0iasoq003BJoWqC0xotZnRpA


###

// Posts a single todo
POST {{host}}/todos
content-type: application/json
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmRmODY2MTVhNzgxMTAwMTY5ZTY2NWYiLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTQxMzc1NTkxfQ.E1yU4fBxX9NmCsAcZBx0iasoq003BJoWqC0xotZnRpA

{
    "text": "Hoje estamos felises mais uma ves"
}

###

// Get a single todo
GET {{host}}/todos/5bdf867f5a781100169e6662
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmRmODY2MTVhNzgxMTAwMTY5ZTY2NWYiLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTQxMzc1NTkxfQ.E1yU4fBxX9NmCsAcZBx0iasoq003BJoWqC0xotZnRpA

###

// Deletes a single todo
DELETE {{host}}/todos/5bdf87f15a781100169e6663
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmRmODY2MTVhNzgxMTAwMTY5ZTY2NWYiLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTQxMzc1NTkxfQ.E1yU4fBxX9NmCsAcZBx0iasoq003BJoWqC0xotZnRpA

###

// Updates a single todo 5bd91253bdcb6d48cc09be9d
PATCH {{host}}/todos/5bdf867f5a781100169e6662
content-type: application/json
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmRmODY2MTVhNzgxMTAwMTY5ZTY2NWYiLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTQxMzc1NTkxfQ.E1yU4fBxX9NmCsAcZBx0iasoq003BJoWqC0xotZnRpA

{
    "completed": true
}