@host = localhost:3000
//@host = cryptic-bastion-36225.herokuapp.com

POST http://{{host}}/users
content-type: application/json

{
    "email": "onildo2@teste.com",
    "password": "456def"
}

###

GET http://{{host}}/users/me
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmRmODQyOTAwNTFmYTE5YmMzY2IwNGYiLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTQxMzc1MzA4fQ.lH-kvE7ARMGChg8C0gOdesQjvBOr6H1IOhXSqWIVA6c

###

POST http://{{host}}/users/login
content-type: application/json

{
    "email": "onildo2@teste.com",
    "password": "456def"
}

###

DELETE http://{{host}}/users/me/token
content-type: application/json
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmRlNDU4Mzg1NWIzYTFiMTQ4MzE3YzUiLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTQxMjkzNDQzfQ.-VBLHKcu2MWtdWpQPPU20_yyP391emADOwjmDK7bU-w
