@host = localhost:3000
// @host = cryptic-bastion-36225.herokuapp.com

POST http://{{host}}/users
content-type: application/json

{
    "email": "abcd@gmail.com",
    "password": "123abc"
}

###

GET http://{{host}}/users/me
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmRhMzUwMTU4N2NhNWFhZTgxMWJjODAiLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTQxMDI3MDczfQ.2UdkvkmpWujzXhEme9CIs2ZCkwTuHzftxP9K4L_CQ5Y