@host = localhost:3000
// @host = cryptic-bastion-36225.herokuapp.com

POST http://{{host}}/users
content-type: application/json

{
    "email": "onim@teste.com",
    "password": "456def"
}

###

GET http://{{host}}/users/me
x-auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmRlNDU4Mzg1NWIzYTFiMTQ4MzE3YzUiLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNTQxMjkzOTM4fQ.3BV4PMSSngUgv0x9fKd040-OzfWwkmEa-h1H-QjbaLo

###

POST http://{{host}}/users/login
content-type: application/json

{
    "email": "onim@teste.com",
    "password": "456def"
}